packages:
  - "."
  - "apps/*"
  - "packages/*"

catalog:
  # Framework
  next: "16.2.1"
  react: "19.2.4"
  react-dom: "19.2.4"
  
  # Type
  typescript: "^5"
  "@types/node": "^20"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  
  # Tailwind
  tailwindcss: "^4"
  "@tailwindcss/postcss": "^4"
  "@tailwindcss/typography": "^0.5.19"
  "tailwind-merge": "^3.5.0"
  
  # AI
  ai: "^6.0.137"
  "@ai-sdk/openai": "^3.0.48"
  "@ai-sdk/react": "^3.0.139"
  
  # DB
  drizzle-orm: "^0.45.2"
  drizzle-kit: "^0.31.10"
  pg: "^8.16.3"
  "@types/pg": "^8.15.6"
  
  # Tools
  eslint: "^9"
  "@antfu/eslint-config": "latest"
  eslint-config-next: "16.2.1"
  skills-npm: "^1.1.1"
  clsx: "^2.1.1"
  date-fns: "^4.1.0"
  lucide-react: "^1.0.1"
  zod: "^4.3.6"
  bcryptjs: "^3.0.3"
  "@types/bcryptjs": "^3.0.0"
  streamdown: "^2.5.0"
  "@streamdown/cjk": "^1.0.3"
  "@streamdown/code": "^1.1.1"
  "@streamdown/math": "^1.0.2"
  "@streamdown/mermaid": "^1.0.2"
  vega: "^6.2.0"
  vega-embed: "^7.1.0"
  vega-lite: "^6.4.2"
  next-auth: "5.0.0-beta.30"
  "@auth/drizzle-adapter": "^1.11.1"
  next-themes: "^0.4.6"
